CREATE TABLE TURMA (
	id BIGINT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	modulo VARCHAR(255) DEFAULT 0
);

CREATE TABLE ESTUDANTE (
	id BIGINT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
    data_nasc DATE NOT NULL,
    turma_id BIGINT,
    FOREIGN KEY (turma_id) REFERENCES TURMA(id)
);

CREATE TABLE HOBBY (
	id BIGINT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ESTUDANTE_HOBBY (
	id BIGINT PRIMARY KEY,
	estudante_id BIGINT NOT NULL,
    FOREIGN KEY (estudante_id) REFERENCES ESTUDANTE(id),
    hobby_id BIGINT NOT NULL,
    FOREIGN KEY (hobby_id) REFERENCES HOBBY(id)
);

CREATE TABLE DOCENTE (
	id BIGINT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
    data_nasc DATE NOT NULL,
    turma_id BIGINT,
    FOREIGN KEY (turma_id) REFERENCES TURMA(id)
);

CREATE TABLE ESPECIALIDADE (
	id BIGINT PRIMARY KEY,
	nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE DOCENTE_ESPECIALIDADE (
	id BIGINT PRIMARY KEY,
	docente_id BIGINT NOT NULL,
    FOREIGN KEY (docente_id) REFERENCES DOCENTE(id),
    especialidade_id BIGINT NOT NULL,
    FOREIGN KEY (especialidade_id) REFERENCES ESPECIALIDADE(id)
);

INSERT
INTO TURMA (id, nome)
VALUES 
	(1, 'Freire'),
    (2, 'Alves'),
    (3, 'Silveira'),
    (4, 'Paulo'),
    (5, 'Pedro');

INSERT
INTO ESPECIALIDADE (id, nome)
VALUES 
	(1, 'JS'),
    (2, 'CSS'),
    (3, 'React'),
    (4, 'Typescript'),
    (5, 'POO');
    
SELECT * FROM DOCENTE;
SELECT * FROM ESPECIALIDADE;
SELECT * FROM TURMA;
SELECT * FROM ESTUDANTE;
SELECT * FROM ESTUDANTE_HOBBY;
SELECT * FROM DOCENTE_ESPECIALIDADE;
SELECT * FROM HOBBY;

/*
SELECT ESTUDANTE.nome, DOCENTE.nome, TURMA.nome, TURMA.id
FROM ESTUDANTE
JOIN TURMA
ON ESTUDANTE.turma_id = TURMA.id
JOIN DOCENTE
ON DOCENTE.turma_id = TURMA.id
WHERE (TURMA.id = 2);

SELECT HOBBY.id, HOBBY.nome, ESTUDANTE.nome
FROM ESTUDANTE_HOBBY
JOIN ESTUDANTE
ON ESTUDANTE_HOBBY.estudante_id = ESTUDANTE.id
JOIN HOBBY
ON HOBBY.id = ESTUDANTE_HOBBY.hobby_id
WHERE (ESTUDANTE_HOBBY.hobby_id = 1662761074397);

SELECT DOCENTE.nome, ESPECIALIDADE.nome
FROM DOCENTE_ESPECIALIDADE
JOIN DOCENTE
ON DOCENTE_ESPECIALIDADE.docente_id = DOCENTE.id
JOIN ESPECIALIDADE
ON ESPECIALIDADE.id = DOCENTE_ESPECIALIDADE.especialidade_id
WHERE (ESPECIALIDADE.nome = "POO");

SELECT *
FROM ESTUDANTE
UNION ALL
SELECT *
FROM DOCENTE
*/

-- DROP TABLE TURMA, ESTUDANTE, HOBBY, ESTUDANTE_HOBBY, DOCENTE, ESPECIALIDADE, DOCENTE_ESPECIALIDADE